service: url-shortener
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  memorySize: 1024
  architecture: arm64
  logRetentionInDays: 7
  deploymentMethod: direct

functions:
  createUrl:
    handler: src/services/create-url/createUrl.handler
    memorySize: ${self:provider.memorySize}
    description: WIP
    events:
      - httpApi:
          path: /url
          method: post

  fetchUrl:
    handler: src/services/fetch-url/fetchUrl.handler
    memorySize: ${self:provider.memorySize}
    description: WIP
    events:
      - httpApi:
          path: /url/{id}
          method: get

  updateUrl:
    handler: src/services/update-url/updateUrl.handler
    memorySize: ${self:provider.memorySize}
    description: WIP
    events:
      - httpApi:
          path: /url/{id}
          method: put

  deleteUrl:
    handler: src/services/delete-url/deleteUrl.handler
    memorySize: ${self:provider.memorySize}
    description: WIP
    events:
      - httpApi:
          path: /url/{id}
          method: delete
